ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'ENDPOINT_CREDENTIAL_ROTATION_STAGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'ENDPOINT_CREDENTIAL_ROTATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CONNECTION_GRANT_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CONNECTION_GRANT_REDEEMED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CONNECTION_GRANT_DENIED';
