/**
 * What the server actually requires of a managed computer's agent.
 *
 * `AGENT_CONTRACT_VERSION` is **the last platform version in which the agent
 * itself changed** — the heartbeat script generated by PublicController — and
 * not the current platform version. Those are different numbers and conflating
 * them was a real bug: the device page compared a reported agent against
 * `version.json`, so shipping any release at all — a README fix included —
 * marked every machine in the fleet as running an outdated agent, beside a
 * button offering to reinstall it.
 *
 * That is crying wolf with a ~40 MB download per machine attached, and it
 * trains people to ignore the one case that matters: an agent genuinely too
 * old to collect an inventory or run a command.
 *
 * **Bump this when, and only when, the generated agent changes** — a new field
 * on the heartbeat, a new command type it must understand, a fix to the
 * collection itself. Check with:
 *
 *     git diff <last-tag>..HEAD -- apps/api/src/public/public.controller.ts
 *
 * History, for the next person deciding whether to move it:
 *   0.14.0  inventory, update scan, event-log query, command queue   (+188)
 *   0.15.0  reports its own version; handles reinstallAgent           (+44)
 *   0.16.x  no agent change                                            (0)
 *   0.17.0  CPU load, live memory and system-disk free space
 */
export const AGENT_CONTRACT_VERSION = '0.17.0';

/**
 * Numeric-segment version compare; tolerates junk by treating it as 0.
 *
 * Returns <0 if `a` is older than `b`, 0 if equal, >0 if newer.
 */
export function compareVersions(a: string, b: string): number {
  const pa = a.replace(/^v/, '').split('.').map((x) => parseInt(x, 10) || 0);
  const pb = b.replace(/^v/, '').split('.').map((x) => parseInt(x, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (d !== 0) return d < 0 ? -1 : 1;
  }
  return 0;
}

/**
 * Is this reported agent version good enough for what the server asks of it?
 *
 * A null or unparseable version is NOT current: that is a machine whose
 * installer predates agent-version reporting altogether, which is by
 * definition older than the contract.
 *
 * An agent *newer* than the contract is fine — a machine installed from a
 * later release than the one that last changed the agent is the normal case,
 * and the commonest one.
 */
export function agentMeetsContract(reported: string | null | undefined): boolean {
  if (!reported) return false;
  return compareVersions(reported, AGENT_CONTRACT_VERSION) >= 0;
}
