import {
  IsArray, IsBoolean, IsEnum, IsInt, IsIP, IsISO8601, IsObject,
  IsOptional, IsString, Length, Matches, Max, Min,
} from 'class-validator';

export enum EndpointAccessMode {
  ASSIGNED_USERS = 'ASSIGNED_USERS',
  COMPANY_WIDE   = 'COMPANY_WIDE',
}

export class CreateClaimTokenDto {
  @IsOptional() @IsString() endpointId?: string;
  @IsOptional() @IsString() customerName?: string;
  @IsOptional() @IsString() siteName?: string;
  @IsOptional() @IsString() @Length(0, 256) description?: string;

  // Managed-computer enrollment binding. All of these travel WITH the token
  // (server-side) so the machine that redeems it cannot pick a different
  // business or assign itself to a different user.
  //
  // `businessId` is the current name; `customerId` is still accepted so a
  // client mid-upgrade keeps working.
  @IsOptional() @IsString() businessId?: string;
  @IsOptional() @IsString() customerId?: string;
  @IsOptional() @IsEnum(EndpointAccessMode) accessMode?: EndpointAccessMode;
  @IsOptional() @IsArray() @IsString({ each: true }) assignedUserIds?: string[];
  @IsOptional() @IsString() endpointGroupId?: string;
}

export class HeartbeatDto {
  @IsString()
  @Matches(/^[0-9]{6,15}$/, { message: 'rustdeskId must be numeric' })
  rustdeskId!: string;

  @IsOptional()
  @IsString()
  @Length(1, 64)
  hostname?: string;

  @IsOptional()
  @IsString()
  @Length(1, 32)
  platform?: string;

  @IsOptional()
  @IsString()
  @Length(1, 64)
  osVersion?: string;

  @IsOptional()
  @IsString()
  @Length(1, 32)
  agentVersion?: string;

  // Installed RustDesk client version, e.g. "1.4.9". Drives the update
  // check on the Updates page and clears a staged update once the endpoint
  // reports the target version.
  @IsOptional()
  @IsString()
  @Length(1, 32)
  rustdeskVersion?: string;

  @IsOptional()
  @IsIP()
  ipAddress?: string;

  // Optional permanent password from the on-device installer. Stored
  // encrypted on the RustdeskNode so that when a platform admin later
  // assigns an unassigned device to a tenant, the tenant already has
  // the password without needing the customer to re-type it.
  @IsOptional()
  @IsString()
  @Length(1, 128)
  password?: string;

  // Per-device secret generated by the installer. Proves the caller is the
  // machine it says it is; see RustdeskNode.agentSecretHash.
  @IsOptional()
  @IsString()
  @Length(16, 128)
  @Matches(/^[A-Za-z0-9_-]+$/, { message: 'agentSecret must be URL-safe base64' })
  agentSecret?: string;

  // Live session state. Cheap enough on the agent (one CIM query) to send on
  // every beat, and it is the first thing a technician looks at before
  // connecting: an empty string means nobody is signed in, which is different
  // from the field being absent.
  @IsOptional()
  @IsString()
  @Length(0, 128)
  loggedOnUser?: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  uptimeSeconds?: number;

  @IsOptional()
  @IsISO8601()
  lastBootAt?: string;

  // Live resource sample. Sent every beat so the device page's gauges are
  // minutes old rather than hours; the slower inventory pass still carries
  // the full per-disk list and everything that does not move.
  @IsOptional() @IsInt() @Min(0) @Max(100) cpuLoadPercent?: number;
  @IsOptional() @IsInt() @Min(0) memoryTotalMb?: number;
  @IsOptional() @IsInt() @Min(0) memoryFreeMb?: number;
  @IsOptional() @IsInt() @Min(0) systemDiskTotalMb?: number;
  @IsOptional() @IsInt() @Min(0) systemDiskFreeMb?: number;
}

/**
 * An endpoint reporting back on a command it was handed.
 *
 * Only one of `inventory` / `updates` / `events` is meaningful, decided by the
 * type of the command being closed out — the server picks the right one from
 * its own row rather than believing whichever field arrived. Each is validated
 * as a shape only; every value inside is clamped by
 * EndpointInventoryService's sanitisers, which is where the real bounds live.
 */
export class CommandResultDto {
  @IsString()
  @Matches(/^[0-9]{6,15}$/, { message: 'rustdeskId must be numeric' })
  rustdeskId!: string;

  @IsString()
  @Length(16, 128)
  @Matches(/^[A-Za-z0-9_-]+$/, { message: 'agentSecret must be URL-safe base64' })
  agentSecret!: string;

  @IsString()
  @Length(1, 64)
  commandId!: string;

  @IsBoolean()
  ok!: boolean;

  @IsOptional() @IsString() @Length(0, 2000) error?: string;
  @IsOptional() @IsObject() inventory?: Record<string, unknown>;
  @IsOptional() @IsObject() updates?: Record<string, unknown>;
  @IsOptional() @IsArray() events?: unknown[];
}

export class ClaimEndpointDto {
  @IsString()
  token!: string;

  @IsString()
  rustdeskId!: string;

  @IsOptional()
  @IsString()
  hostname?: string;

  @IsOptional()
  @IsString()
  platform?: string;

  @IsOptional()
  @IsString()
  osVersion?: string;

  @IsOptional()
  @IsString()
  agentVersion?: string;

  @IsOptional()
  @IsString()
  password?: string;

  // Per-device secret generated by the installer. Proves the caller is the
  // machine it says it is; see RustdeskNode.agentSecretHash.
  @IsOptional()
  @IsString()
  @Length(16, 128)
  @Matches(/^[A-Za-z0-9_-]+$/, { message: 'agentSecret must be URL-safe base64' })
  agentSecret?: string;
}
